# Generated by Django 5.2.7 on 2025-10-24 19:18

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="registration_date",
            field=models.DateField(default=patients.models.get_current_date),
        ),
        migrations.AlterField(
            model_name="visitforma",
            name="visit_date",
            field=models.DateField(default=patients.models.get_current_date),
        ),
        migrations.AlterField(
            model_name="visitformb",
            name="visit_date",
            field=models.DateField(default=patients.models.get_current_date),
        ),
        migrations.AlterField(
            model_name="vitals",
            name="visit_date",
            field=models.DateField(default=patients.models.get_current_date),
        ),
    ]
